import = ["~/.config/alacritty/local.toml"]
live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

# cursor colors
[colors]
cursor = { text = 'CellBackground', cursor = '#f5dcd8' }
selection = { text = '#26233a', background = '#e0def4' }
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#1e1e1e'
foreground = '#908caa'

# Normal colors
[colors.normal]
black = '#000000'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#eba4ac'
cyan = '#9ccfd8'
white = '#e0def4'

# Bright colors
[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#eba4ac'
cyan = '#9ccfd8'
white = '#e0def4'

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
opacity = 0.90
blur = true
decorations_theme_variant = "Dark"
resize_increments = true

[window.dimensions]
columns = 80
lines = 28

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
