theme = "github_dark"

[editor]
line-number = "relative"
mouse = true
cursorline = true
color-modes = true
auto-format = true
bufferline = "multiple"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right =  ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
F = "file_picker_in_current_directory"
